In [2]:
from flowise import Flowise, PredictionData
import pandas as pd
import requests

In [ ]:
# df = pd.read_excel("qa_par.xlsx",
#                    sheet_name="Sheet1",
#                    engine="openpyxl"
#                    )
# df.head()

,Question,True answer,Real answer,Note,Status
0,Chính sách học bổng của trường,Chính sách học bổng\n1. Học bổng CMC Khai phón...,NaN,NaN,NaN
1,Có bao nhiêu phương thức xét tuyển,"Năm 2024, Trường Đại học CMC xét tuyển theo 5 ...",NaN,NaN,NaN
2,Nộp hồ sơ đăng ký xét tuyển,Cách 1: Nộp hồ sơ trực tuyến.\nBước 1: Thí sin...,NaN,NaN,NaN
3,Các khoản phí cần nộp khi nhập học,Khoản học phí tạm thu lần đầu: 11.054.520 đồng...,NaN,NaN,NaN

In [29]:
# df.loc[df["Status"].isna(), "Status"] = "Incomplete"
# df.head()

/tmp/ipykernel_88333/3569615800.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Incomplete' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["Status"].isna(), "Status"] = "Incomplete"

,Question,True answer,Real answer,Note,Status
0,Chính sách học bổng của trường,Chính sách học bổng\n1. Học bổng CMC Khai phón...,NaN,NaN,Incomplete
1,Có bao nhiêu phương thức xét tuyển,"Năm 2024, Trường Đại học CMC xét tuyển theo 5 ...",NaN,NaN,Incomplete
2,Nộp hồ sơ đăng ký xét tuyển,Cách 1: Nộp hồ sơ trực tuyến.\nBước 1: Thí sin...,NaN,NaN,Incomplete
3,Các khoản phí cần nộp khi nhập học,Khoản học phí tạm thu lần đầu: 11.054.520 đồng...,NaN,NaN,Incomplete

In [32]:
df = pd.read_csv("data/qa-pair.csv")
df.head()

,Question,True answer,Real answer,Score,Note,Status
0,Chính sách học bổng của trường,Chính sách học bổng\n1. Học bổng CMC Khai phón...,NaN,NaN,NaN,NaN
1,Có bao nhiêu phương thức xét tuyển,"Năm 2024, Trường Đại học CMC xét tuyển theo 5 ...",NaN,NaN,NaN,NaN
2,Nộp hồ sơ đăng ký xét tuyển,Cách 1: Nộp hồ sơ trực tuyến.\nBước 1: Thí sin...,NaN,NaN,NaN,NaN
3,Các khoản phí cần nộp khi nhập học,Khoản học phí tạm thu lần đầu: 11.054.520 đồng...,NaN,NaN,NaN,NaN

In [33]:
df.loc[df["Status"].isna(), "Status"] = "incomplete"
df.head()

/tmp/ipykernel_88333/4096478739.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'incomplete' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["Status"].isna(), "Status"] = "incomplete"

,Question,True answer,Real answer,Score,Note,Status
0,Chính sách học bổng của trường,Chính sách học bổng\n1. Học bổng CMC Khai phón...,NaN,NaN,NaN,incomplete
1,Có bao nhiêu phương thức xét tuyển,"Năm 2024, Trường Đại học CMC xét tuyển theo 5 ...",NaN,NaN,NaN,incomplete
2,Nộp hồ sơ đăng ký xét tuyển,Cách 1: Nộp hồ sơ trực tuyến.\nBước 1: Thí sin...,NaN,NaN,NaN,incomplete
3,Các khoản phí cần nộp khi nhập học,Khoản học phí tạm thu lần đầu: 11.054.520 đồng...,NaN,NaN,NaN,incomplete

In [34]:
df.to_csv("data/qa-pair.csv")